_target_            : lfads_torch.post_run.fewshot_analysis.FewshotTrainTest
fewshot_head_model  : ???
fewshot_trainer     : ???
K                   : ???
ratio               : 0.3
seed                : 0
log_every_n_epochs  : ${log_every_n_epochs_fewshot}
fewshot_trainer_epochs: 50