defaults:
  - fewshot_callbacks@fewshot_k10_seed0: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed1: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed2: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed3: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed4: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed5: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed6: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed7: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed8: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed9: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed10: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed11: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed12: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed13: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed14: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed15: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed16: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed17: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed18: fewshot_base
  - fewshot_callbacks@fewshot_k10_seed19: fewshot_base
  - fewshot_callbacks@fewshot_k50_seed20: fewshot_base
  - fewshot_callbacks@fewshot_k50_seed21: fewshot_base
  - fewshot_callbacks@fewshot_k50_seed22: fewshot_base
  - fewshot_callbacks@fewshot_k50_seed23: fewshot_base
  - fewshot_callbacks@fewshot_k50_seed24: fewshot_base
  - _self_

fewshot_k10_seed0:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 0
  use_recon_as_targets: true
fewshot_k10_seed1:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 1
  use_recon_as_targets: true
fewshot_k10_seed10:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 10
  use_recon_as_targets: true
fewshot_k10_seed11:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 11
  use_recon_as_targets: true
fewshot_k10_seed12:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 12
  use_recon_as_targets: true
fewshot_k10_seed13:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 13
  use_recon_as_targets: true
fewshot_k10_seed14:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 14
  use_recon_as_targets: true
fewshot_k10_seed15:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 15
  use_recon_as_targets: true
fewshot_k10_seed16:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 16
  use_recon_as_targets: true
fewshot_k10_seed17:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 17
  use_recon_as_targets: true
fewshot_k10_seed18:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 18
  use_recon_as_targets: true
fewshot_k10_seed19:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 19
  use_recon_as_targets: true
fewshot_k10_seed2:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 2
  use_recon_as_targets: true
fewshot_k10_seed3:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 3
  use_recon_as_targets: true
fewshot_k10_seed4:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 4
  use_recon_as_targets: true
fewshot_k10_seed5:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 5
  use_recon_as_targets: true
fewshot_k10_seed6:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 6
  use_recon_as_targets: true
fewshot_k10_seed7:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 7
  use_recon_as_targets: true
fewshot_k10_seed8:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 8
  use_recon_as_targets: true
fewshot_k10_seed9:
  K: 10
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 9
  use_recon_as_targets: true
fewshot_k50_seed20:
  K: 50
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 20
  use_recon_as_targets: true
fewshot_k50_seed21:
  K: 50
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 21
  use_recon_as_targets: true
fewshot_k50_seed22:
  K: 50
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 22
  use_recon_as_targets: true
fewshot_k50_seed23:
  K: 50
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 23
  use_recon_as_targets: true
fewshot_k50_seed24:
  K: 50
  eval_type: post_run
  fewshot_head_model: ${fewshot_head_model_lightning}
  fewshot_trainer: ${fewshot_trainer}
  fewshot_trainer_epochs: 150
  log_every_n_epochs: 1
  seed: 24
  use_recon_as_targets: true
