defaults:
  - multi
  - fewshot_head_model: linear
  - _self_

new_heldout_units: 23
# old_heldout_units: ${eval:${model.readout.modules[0].out_features}-${model.encod_data_dim}}
fewshot_neurons: 22

datamodule:
  _target_: lfads_torch.datamodules_fewshot.DoubleHeldoutDataModule
  split_keep_first: true
  num_new_heldout_neurons: ${new_heldout_units}
  attr_keys:
    - psth
    - train_cond_idx
    - valid_cond_idx
    - train_decode_mask
    - valid_decode_mask
    - train_fewshot_data
    - valid_fewshot_data

model:
  _target_: lfads_torch.model.StoreOutputsLFADS
  readout:
    modules:
      - _target_: lfads_torch.modules.readin_readout.FanInLinear
        in_features: ${model.fac_dim}
        out_features: ${eval:${model.encod_data_dim} + ${new_heldout_units}}




callbacks:
#  fewshot10:
#    _target_            : lfads_torch.post_run.fewshot_analysis.FewshotTrainTest
#    fewshot_head_model  : ${fewshot_head_model}
#    fewshot_trainer     : ${fewshot_trainer}
#    K                   : 10
#    ratio               : 0.3
#    seed                : 0
#    log_every_n_epochs  : 5
#    fewshot_trainer_epochs: 50
#
#  fewshot100:
#    _target_            : lfads_torch.post_run.fewshot_analysis.FewshotTrainTest
#    fewshot_head_model  : ${fewshot_head_model}
#    fewshot_trainer     : ${fewshot_trainer}
#    K                   : 100
#    ratio               : 0.3
#    seed                : 0
#    log_every_n_epochs  : 5
#    fewshot_trainer_epochs: 50

  fewshot1000_reallyheldout:
    _target_            : lfads_torch.post_run.fewshot_analysis.FewshotTrainTest
    fewshot_head_model  : ${fewshot_head_model}
    fewshot_trainer     : ${fewshot_trainer}
    K                   : 1000
    ratio               : 0.3
    seed                : 0
    log_every_n_epochs  : 5
    fewshot_trainer_epochs: 50

  fewshot1000_recon:
    _target_            : lfads_torch.post_run.fewshot_analysis.FewshotTrainTest
    fewshot_head_model  : ${fewshot_head_model}
    fewshot_trainer     : ${fewshot_trainer}
    K                   : 1000
    ratio               : 0.3
    seed                : 0
    log_every_n_epochs  : 5
    fewshot_trainer_epochs: 50
    use_recon_as_target : true



fewshot_trainer:
  _target_: pytorch_lightning.Trainer
  _partial_: true
  max_epochs: 50
  log_every_n_steps: 5
