defaults:
  - nlb_mc_rtt
  - _self_

_target_: lfads_torch.datamodules_fewshot.DoubleHeldoutDataModule
split_keep_first: true
num_new_heldout_neurons: ${new_heldout_units}
batch_keys:
  - behavior
  - fewshot_data
data_paths:
  - ${relpath:datasets/mc_rtt-05ms-val.h5}
attr_keys:
  - train_decode_mask
  - valid_decode_mask
  - train_fewshot_data
  - valid_fewshot_data
batch_size: 256
